export default {
  discussion: {
    loading: false,
    data: null,
    error: null,
    success: false,
    createLoading: false,
    createData: null,
    createError: null,
    singleDiscData: null,
    discussionLoading: false,
    discussionData: null,
    starterPromptLoading: false,
    starterPromptData: null,
    postInspLoading: false,
    postInspData: null,
    scoreLoading: false,
    scoreData: null,
    calendarLoading: false,
    calendarData: null,
    joinLoading: false,
    joinData: null,
    joinSuccess: false,
    joinError: null,
    postLoading: false,
    postSuccess: false,
    postError: null,
    autoScoringData: null,
  },
};
