export const CREATE_DISCUSSION_LOADING = "CREATE_DISCUSSION_LOADING";
export const CREATE_DISCUSSION_SUCCESS = "CREATE_DISCUSSION_SUCCESS";
export const CREATE_DISCUSSION_ERROR = "CREATE_DISCUSSION_ERROR";
